[package]
name = "cernan"
version = "0.1.0"
authors = ["Brian L. Troutwine <blt@postmates.com>"]

[dependencies]
docopt = "0.6.80"
histogram = "*"
hyper = "0.9.6"
mime = "0.2.0"
rustc-serialize = "0.3.19"
time = "0.1"
url = "1.1.1"
